Feature/apply opa info in jpa queries
FINTLabs/fint-kontroll-role-catalog pull request #2
Opened 2023-09-14 09:33 UTC by berntjoh

2023-09-15 05:37 UTC, sourcecodeas requested changes
Ser bra ut det her Erling. Testene ser supre ut. Jeg har lagt inn litt kommentarer her og der på noen småting som hadde vært kjekt å fikse før den merges.

2023-09-15 05:37 UTC, sourcecodeas commented on src/main/java/no/fintlabs/role/RoleController.java
Tror vi skal gjøre et forsøk på å ikke bruke authorizationclient i controlleren her. Den kan like gjerne injectes der den skal brukes, i servicen, så slipper vi å ha resultatet som parameter videre..

2023-09-15 05:37 UTC, sourcecodeas commented on src/main/java/no/fintlabs/role/RoleController.java
> +        return roleResponseFactory.toResponseEntity(FintJwtEndUserPrincipal.from(jwt),search,orgUnits, orgUnitsInScope, roleType,aggRoles,page,size);
Ser det er gjort samme her som i orgunit og user. Riktig at vi bruker responsefactory, men den skal bare brukes til å lage objekter. Så her burde service vært kalt først, og så responsefactory etterpå.

Tenker vi kan ta en liten session en dag å se på det, trengs ikke endres nå.

2023-09-15 05:37 UTC, sourcecodeas commented on src/main/java/no/fintlabs/role/RoleService.java
getSimpleRoles er litt lang og litt mye if/else. Tenker den fint kan deles opp med et par private metoder. For eksempel:

```suggestion
public List<SimpleRole> getSimpleRoles(
            FintJwtEndUserPrincipal principal,
            String search,
            List<String> orgUnits,
            List<String> orgUnitsInScope,
            String roleType,
            Boolean aggRoles
    ) {
        List<String> orgUnitsInSearch = getOrgUnitsInSearch(orgUnits, orgUnitsInScope);
        List<Role> roles = getRoles(search, orgUnitsInSearch, roleType, aggRoles);
        return roles.stream().map(Role::toSimpleRole).collect(Collectors.toList());
    }

    private List<String> getOrgUnitsInSearch(List<String> orgUnits, List<String> orgUnitsInScope) {
        if (orgUnits == null) {
            log.info("OrgUnits parameter is empty, using orgunits from scope {} in search", orgUnitsInScope);
            return orgUnitsInScope;
        } else {
            log.info("OrgUnits parameter list: {}", orgUnits);
            List<String> filteredOrgUnits = orgUnits.stream()
                    .filter(orgUnitsInScope::contains)
                    .collect(Collectors.toList());
            log.info("OrgUnits in search: {}", filteredOrgUnits);
            return filteredOrgUnits;
        }
    }

    private List<Role> getRoles(String search, List<String> orgUnitsInSearch, String roleType, Boolean aggRoles) {
        if ("ALLTYPES".equals(roleType)) {
            if (aggRoles == null) {
                return roleRepository.getRolesByNameOrgunitsAggregated(search, orgUnitsInSearch);
            }
            return roleRepository.getRolesByNameOrgunitsAggregated(search, orgUnitsInSearch, aggRoles);
        }

        if (aggRoles == null) {
            return roleRepository.getRolesByNameTypeOrgunitsAggregated(search, roleType, orgUnitsInSearch);
        }
        return roleRepository.getRolesByNameTypeOrgunitsAggregated(search, roleType, orgUnitsInSearch, aggRoles);
    }
```

2023-09-15 05:37 UTC, sourcecodeas commented on src/test/java/no/fintlabs/role/RoleServiceTests.java
> +import java.util.*;
Ikke anbefalt å ha stjerne imports. Intellij har en egen shortcut (Ctrl + Alt + 0) som fikser det i filen.

2023-09-15 05:37 UTC, sourcecodeas commented on src/test/java/no/fintlabs/role/RoleServiceTests.java
> +
Fjerne system prints

2023-09-15 05:37 UTC, sourcecodeas commented on src/test/java/no/fintlabs/role/RoleServiceTests.java
> +        role = Role.builder()
Ser ut som at role som lages her brukes bare i 1 test? Setup metoden kjøres før hver test, så tanken med metoden er å ha ting som skal gjenbrukes/gjøres før hver test. 

Du lager newRole et par steder, kanskje en privat metode for å opprette role kunne vært noe?

2023-09-19 10:30 UTC, berntjoh commented on src/main/java/no/fintlabs/role/RoleService.java
>      public Mono<Role> createNewRole(Role role) {
Mono fjernet her 
Å opprette nye roller som ikke er tilgangsroller, blir ikke implementert foreløpig. Men vil antakelig komme senere

2023-09-19 13:40 UTC, berntjoh commented on src/test/java/no/fintlabs/role/RoleServiceTests.java
> +import java.util.*;
Fixed

2023-09-19 13:43 UTC, berntjoh commented on src/test/java/no/fintlabs/role/RoleServiceTests.java
> +
Fixed

2023-09-19 14:01 UTC, berntjoh commented on src/main/java/no/fintlabs/role/RoleController.java
> +        return roleResponseFactory.toResponseEntity(FintJwtEndUserPrincipal.from(jwt),search,orgUnits, orgUnitsInScope, roleType,aggRoles,page,size);
Vi ser på det sammen

2023-09-21 07:00 UTC, sourcecodeas approved these changes
Knallfint nå 😊

2023-09-26 07:49 UTC, merged